import React from "react";

const DataDeletionPolicy: React.FC = () => {
  return (
    <div className="p-6 sm:p-10 bg-gradient-to-r from-black via-gray-800 to-black text-white font-sans rounded-lg shadow-lg">
      <h1 className="text-4xl font-extrabold text-center text-teal-400 mb-6">
        Data Deletion Policy for Swasthi
      </h1>
      <p className="mb-4 text-sm text-gray-400 text-center">
        <strong>Last Updated: 09.11.2024</strong>
      </p>
      <p className="mb-6 text-gray-300">
        At Swasthi, we are committed to ensuring that our users have control over their personal data. This Data Deletion Policy outlines the processes and procedures for the deletion of your personal information collected and stored by the Swasthi mobile application (&quot;App&quot;). By using our App, you agree to the terms described in this policy. If you do not agree with this policy, please do not use the App.
      </p>

      <h2 className="text-2xl font-semibold text-teal-300 mb-4">1. User Rights to Data Deletion</h2>

      <h3 className="text-xl font-medium text-yellow-300 mb-2">1.1 Right to Erasure:</h3>
      <p className="mb-4 text-gray-300">
        Users have the right to request the deletion of their personal data that has been collected and stored by the App. This right is in line with data protection regulations, including the General Data Protection Regulation (GDPR) and other applicable data collection laws of India.
      </p>

      <h3 className="text-xl font-medium text-yellow-300 mb-2">1.2 Types of Data Eligible for Deletion:</h3>
      <ul className="list-disc pl-6 mb-6 space-y-2 text-gray-300">
        <li>
          <strong>Personal Information:</strong> Data provided during registration or use of the App, such as email address, username, height, weight, age, and gender.
        </li>
        <li>
          <strong>Usage Data:</strong> Information generated by your use of the App, including interaction data, logs, and preferences.
        </li>
        <li>Any other personal information processed by the App.</li>
      </ul>

      <h2 className="text-2xl font-semibold text-teal-300 mb-4">2. How to Request Data Deletion</h2>

      <h3 className="text-xl font-medium text-yellow-300 mb-2">2.1 Submitting a Request:</h3>
      <p className="mb-4 text-gray-300">
        To request the deletion of your data, please contact us via email at 
        <a href="mailto:help.swasthi@gmail.com" className="text-blue-500 hover:underline"> help.swasthi@gmail.com </a>
        or 
        <a href="mailto:info@swasthi.fit" className="text-blue-500 hover:underline"> info@swasthi.fit </a>
        with the subject line &quot;Data Deletion Request.&quot; Include the following information in your request:
      </p>
      <ul className="list-disc pl-6 mb-6 space-y-2 text-gray-300">
        <li>Your full name.</li>
        <li>Registered email address associated with your Swasthi account.</li>
        <li>A description of the data you wish to delete.</li>
        <li>A statement confirming that you are the owner of the account.</li>
      </ul>

      <h3 className="text-xl font-medium text-yellow-300 mb-2">2.2 Verification Process:</h3>
      <p className="mb-6 text-gray-300">
        Once a data deletion request is received, we will verify the identity of the requestor to ensure that the person making the request is the account holder or an authorized representative. Verification may include sending an email to the registered email address, requesting confirmation of account information, or requiring additional documentation to confirm your identity.
      </p>

      <h2 className="text-2xl font-semibold text-teal-300 mb-4">3. Timeframe for Data Deletion</h2>

      <h3 className="text-xl font-medium text-yellow-300 mb-2">3.1 Processing Time:</h3>
      <p className="mb-4 text-gray-300">
        Upon successful verification of your identity, we will process your data deletion request within 7 calendar days. In certain situations, such as when the request is complex or involves a large volume of data, this period may be extended by an additional 4 - 6 weeks. We will inform you of any such extension and the reasons for the delay.
      </p>

      <h3 className="text-xl font-medium text-yellow-300 mb-2">3.2 Notification of Deletion:</h3>
      <p className="mb-6 text-gray-300">
        You will receive a confirmation email once your data has been deleted. This notification will provide details of the data deleted and the date of deletion.
      </p>

      <h2 className="text-2xl font-semibold text-teal-300 mb-4">4. Consequences of Data Deletion</h2>

      <h3 className="text-xl font-medium text-yellow-300 mb-2">4.1 Account Termination:</h3>
      <p className="mb-4 text-gray-300">
        Deleting your personal data will result in the termination of your Swasthi account. You will no longer have access to the App, including any data, features, or subscriptions associated with your account.
      </p>

      <h3 className="text-xl font-medium text-yellow-300 mb-2">4.2 Loss of Data and Services:</h3>
      <p className="mb-4 text-gray-300">
        Once your data is deleted, it cannot be recovered. All health metrics, progress, preferences, and any other data associated with your account will be permanently erased.
      </p>

      <h3 className="text-xl font-medium text-yellow-300 mb-2">4.3 Impact on Subscriptions:</h3>
      <p className="mb-6 text-gray-300">
        If you have an active subscription, deleting your account will result in the immediate termination of your subscription. No refunds will be issued for any unused portion of the subscription period.
      </p>

      <h2 className="text-2xl font-semibold text-teal-300 mb-4">5. Exceptions to Data Deletion</h2>

      <h3 className="text-xl font-medium text-yellow-300 mb-2">5.1 Retention for Legal Compliance:</h3>
      <p className="mb-6 text-gray-300">
        Certain data may be retained for a limited period to comply with legal obligations, resolve disputes, enforce our terms and conditions, or protect our legal rights. This may include retaining data required for accounting, auditing, and regulatory compliance purposes.
      </p>

      <h2 className="text-2xl font-semibold text-teal-300 mb-4">6. Changes to This Data Deletion Policy</h2>

      <h3 className="text-xl font-medium text-yellow-300 mb-2">6.1 Policy Updates:</h3>
      <p className="mb-6 text-gray-300">
        We may update this Data Deletion Policy from time to time to reflect changes in our practices, legal requirements, or operational needs. We will notify you of any significant changes through in-app notifications or other means. Your continued use of the App after the effective date of the updated policy constitutes your acceptance of the changes.
      </p>

      <h2 className="text-2xl font-semibold text-teal-300 mb-4">7. Contact Information</h2>

      <h3 className="text-xl font-medium text-yellow-300 mb-2">7.1 Contact Us:</h3>
      <p className="mb-4 text-gray-300">
        If you have any questions, concerns, or requests regarding this Data Deletion Policy or your personal information, please contact us at:
      </p>
      <p className="text-gray-300">
        Email: <a href="mailto:help.swasthi@gmail.com" className="text-blue-500 hover:underline">help.swasthi@gmail.com</a> or 
        <a href="mailto:info@swasthi.fit" className="text-blue-500 hover:underline">info@swasthi.fit</a><br />
        Address: 395, Purav Deen Dayal, Old Railway Road, Veer Bhawan Nagar, Roorkee-247667, India
      </p>
    </div>
  );
};

export default DataDeletionPolicy;
